### ISSUE TITLE
Choice2Type Can't Search for value in a Modal

### ISSUE THREAD

**Issue by Tquentel** [acantepie/umbrella-admin-demo#3]
It is impossible to click on the input and search for a value in a modal

How to reproduce 

Go to : [umbrella-demo](https://umbrella-corp.dev/admin/datatable/editable)

Click on "Add", next on input "Mission Status"
When you want to search and focus the input, nothing happen

**Comment by acantepie** [comment]
https://github.com/acantepie/umbrella-core/commit/05d58afce55b506d663cd07c9dac29cbe2b4a8cc
