### ISSUE TITLE
Logo is hidden in condensed mode

### ISSUE THREAD

**Issue by Tquentel** [acantepie/umbrella-admin-demo#4]
When window is in condensed mode the logo is hidden 

body[data-leftbar-compact-mode=condensed] .logo span.logo-lg {
    display: none;
}
<img width="473" alt="Screenshot 2021-03-30 at 23 13 54" src="https://user-images.githubusercontent.com/20561169/113057653-99c31200-91ad-11eb-86bc-6fab8d6b57cf.png">

How to Reproduce:

Go to BO and reduce the size of the window 
The logo disappear

**Comment by acantepie** [comment]
Fixed by : https://github.com/acantepie/umbrella-admin/commit/a022a5e458dc830d862d7a02ab6c1d137ad29ef3
Example :

```
umbrella_admin:
  theme:
    logo-sm: 'foo/bar.png'
```
